var listofAddOns =
            [{
                id: 1,
                name: 'Dashboard- $30 per user per month',
                isChecked: false,
                description: 'Key Safety Performance Indicators and Metrics',
                longdescription: "IndustrySafe's Dashboard enables senior executives, managers, and safety professionals to view key safety performance metrics. Users can drill down on these metrics and configure the Dashboard to display their top indicators.",
                perUserFees: 'Yes',
                monthlyFee: 30,
                oneTimeFee: '',
                oneTimeFeeCategory: '',
                hoursConfiguraitonAssistance: 2,
                hoursEHSAdminTraining: 2,
                hoursEndUserWebinars: 2,
                hoursEndUserTraining: 2,
                ischildElement: false,
                childElementTitle: '',
                childElementSubTitle: '',
                childElementbutton: '',
                childElements: []
            },
            {
                id: 2,
                name: 'Public Web Forms- $210 per month',
                isChecked: false,
                description: 'Allows for easy data entry by multiple stakeholders',
                longdescription: '',
                perUserFees: '',
                monthlyFee: '',
                oneTimeFee: '',
                oneTimeFeeCategory: '',
                hoursConfiguraitonAssistance: '',
                hoursEHSAdminTraining: '',
                hoursEndUserWebinars: '',
                hoursEndUserTraining:'',
                ischildElement: true,
                childElementTitle: 'Public Web Forms',
                childElementSubTitle: 'Select Your Public Web Forms',
                childElementbutton: 'Add Forms',
                childElements: [{
                    id: 1,
                    name: 'Incident Public Web Form',
                    isChecked: false,
                    description: 'Stakeholders can report incidents from any location via the web. No login, username or password is required.',
                    longdescription: 'The Incident Public Web Form enables organizations to have all stakeholders report incidents from any location. Stakeholders simply go to the web to report the incident. No login, username or password is required. The incident data is automatically transferred to IndustrySafe, and IndustrySafe users are automatically notified by email of the incident.',
                    perUserFees: 'No',
                    monthlyFee: 210,
                    oneTimeFee: '',
                    oneTimeFeeCategory: '',
                    hoursConfiguraitonAssistance: 2,
                    hoursEHSAdminTraining: 1,
                    hoursEndUserWebinars: 2,
                    hoursEndUserTraining: 2
                },
                {
                    id: 2,
                    name: 'Hazard Public Web Form',
                    isChecked: false,
                    description: 'Stakeholders can report hazards from any location via the web. No login, username or password is required.',
                    longdescription: 'The Hazard Public Web Form enables organizations to have all stakeholders report hazards from any location. Stakeholders simply go to the web to report the hazard. No login, username or password is required. The hazard data is automatically transferred to IndustrySafe, and IndustrySafe users are automatically notified by email of the hazard.',
                    perUserFees: 'No',
                    monthlyFee: 210,
                    oneTimeFee: '',
                    oneTimeFeeCategory: '',
                    hoursConfiguraitonAssistance: 2,
                    hoursEHSAdminTraining: 1,
                    hoursEndUserWebinars: 2,
                    hoursEndUserTraining: 2
                },
                {
                    id: 3,
                    name: 'Observation Public Web Form',
                    isChecked: false,
                    description: 'Stakeholders can report observations from any location via the web. No login, username or password is required.',
                    longdescription: 'The Observation Public Web Form enables organizations to have all stakeholders report observations from any location. Stakeholders simply go to the web to report the observation. No login, username or password is required. The observation data is automatically transferred to IndustrySafe.',
                    perUserFees: 'No',
                    monthlyFee: 210,
                    oneTimeFee: '',
                    oneTimeFeeCategory: '',
                    hoursConfiguraitonAssistance: 2,
                    hoursEHSAdminTraining: 1,
                    hoursEndUserWebinars: 2,
                    hoursEndUserTraining: 2
                }]
            },
            {
                id: 3,
                name: 'Interfaces- $70 per month plus interface fees',
                isChecked: false,
                description: 'Connections with other systems for key data',
                longdescription: '',
                perUserFees: '',
                monthlyFee: '',
                oneTimeFee: '',
                oneTimeFeeCategory: '',
                hoursConfiguraitonAssistance: '',
                hoursEHSAdminTraining: '',
                hoursEndUserWebinars: '',
                hoursEndUserTraining: '',
                ischildElement: true,
                childElementTitle: 'Interfaces',
                childElementSubTitle: 'Select Your Interfaces',
                childElementbutton: 'Add Interfaces',
                childElements: [{
                    id: 1,
                    name: 'Employee Interface',
                    isChecked: false,
                    description: 'Automatically update employee data in IndustrySafe by sending a flat file of Employee data on a regular basis',
                    longdescription: 'Customers export employee human resource information via secure FTP (according to a standard format) to an IndustrySafe directory.  IndustrySafe will read the data in the directory and automatically import the data into IndustrySafe. System audit logs are available to confirm the success/failure of the import(s). TRA will provide specifications to customer on the IndustrySafe employee data format and provide technical assistance to customer. Customer is responsible for developing the data export in specified format with technical assistance from TRA',
                    perUserFees: 'No',
                    monthlyFee: 70,
                    oneTimeFee: 1500,
                    oneTimeFeeCategory: 'Interface Setup',
                    hoursConfiguraitonAssistance: 12,
                    hoursEHSAdminTraining: '',
                    hoursEndUserWebinars: '',
                    hoursEndUserTraining: ''
                },
                {
                    id: 2,
                    name: 'Single Sign On',
                    isChecked: false,
                    description: 'Allow IndustrySafe users to use network authentication for easy login',
                    longdescription: "Users often have multiple user names and passwords to remember to login to various software tools.  With IndustrySafe's secure single sign on process, users on a secure intranet can automatically be logged into IndustrySafe without having to login again.  TRA will use a Single Sign On Process based on TRA specifications (TRA Specifications are SAML 2.0 Compliant) and work with Customer to test the Single Sign On Process.  Customer is responsible for providing appropriate Single Sign on Authentication code to TRA and assist in testing.",
                    perUserFees: 'No',
                    monthlyFee: 70,
                    oneTimeFee: 1500,
                    oneTimeFeeCategory: 'Interface Setup',
                    hoursConfiguraitonAssistance: 12,
                    hoursEHSAdminTraining: '',
                    hoursEndUserWebinars: '',
                    hoursEndUserTraining: ''
                },
                {
                    id: 3,
                    name: 'Facility Interface',
                    isChecked: false,
                    description: 'Automatically update facility data in IndustrySafe by sending IndustrySafe a flat file of locational data on a regular basis',
                    longdescription: 'Customers export facility and/or locational information via secure FTP (according to a standard format) to an IndustrySafe directory.  IndustrySafe will read the data in the directory and automatically import the data into IndustrySafe. System audit logs are available to confirm the success/failure of the import(s). TRA will provide specifications to customer on the IndustrySafe facility data format and provide technical assistance to customer. Customer is responsible for developing the data export in specified format with technical assistance from TRA.',
                    perUserFees: 'No',
                    monthlyFee: 70,
                    oneTimeFee: 1500,
                    oneTimeFeeCategory: 'Interface Setup',
                    hoursConfiguraitonAssistance: 12,
                    hoursEHSAdminTraining: '',
                    hoursEndUserWebinars: '',
                    hoursEndUserTraining: ''
                },
                {
                    id: 4,
                    name: 'Hours Interface',
                    isChecked: false,
                    description: 'Automatically update hours data in IndustrySafe by sending IndustrySafe a flat file of hours data on a regular basis',
                    longdescription: 'Customers export hours worked information via secure FTP (according to a standard format) to an IndustrySafe directory.  IndustrySafe will read the data in the directory and automatically import the data into IndustrySafe. System audit logs are available to confirm the success/failure of the import(s). TRA will provide specifications to customer on the IndustrySafe hours data format and provide technical assistance to customer. Customer is responsible for developing the data export in specified format with technical assistance from TRA.',
                    perUserFees: 'No',
                    monthlyFee: 70,
                    oneTimeFee: 1500,
                    oneTimeFeeCategory: 'Interface Setup',
                    hoursConfiguraitonAssistance: 12,
                    hoursEHSAdminTraining: '',
                    hoursEndUserWebinars: '',
                    hoursEndUserTraining: ''
                },
                {
                    id: 5,
                    name: 'Incident Interface',
                    isChecked: false,
                    description: 'Automatically update Incident data in IndustrySafe by sending IndustrySafe a flat file of incident data on a regular basis',
                    longdescription: 'Customers export incident information via secure FTP (according to a standard format) to an IndustrySafe directory.  IndustrySafe will read the data in the directory and automatically import the data into IndustrySafe. System audit logs are available to confirm the success/failure of the import(s). TRA will provide specifications to customer on the IndustrySafe incident data format and provide technical assistance to customer. Customer is responsible for developing the data export in specified format with technical assistance from TRA.',
                    perUserFees: 'No',
                    monthlyFee: 70,
                    oneTimeFee: 1500,
                    oneTimeFeeCategory: 'Interface Setup',
                    hoursConfiguraitonAssistance: 12,
                    hoursEHSAdminTraining: '',
                    hoursEndUserWebinars: '',
                    hoursEndUserTraining: ''
                },
                {
                    id: 6,
                    name: 'Training Interface',
                    isChecked: false,
                    description: 'Automatically update training data in IndustrySafe by sending IndustrySafe a flat file of training data on a regular basis',
                    longdescription: 'Customers export training information via secure FTP (according to a standard format) to an IndustrySafe directory.  IndustrySafe will read the data in the directory and automatically import the data into IndustrySafe. System audit logs are available to confirm the success/failure of the import(s). TRA will provide specifications to customer on the IndustrySafe training data format and provide technical assistance to customer. Customer is responsible for developing the data export in specified format with technical assistance from TRA.',
                    perUserFees: 'No',
                    monthlyFee: 70,
                    oneTimeFee: 1500,
                    oneTimeFeeCategory: 'Interface Setup',
                    hoursConfiguraitonAssistance: 12,
                    hoursEHSAdminTraining: '',
                    hoursEndUserWebinars: '',
                    hoursEndUserTraining: ''
                }]
            },
        {
            id: 4,
            name: 'Select Additional Training Services',
            isChecked: false,
            description: 'Additional training or configuration assistance above standard package',
            longdescription: '',
            perUserFees: '',
            monthlyFee: '',
            oneTimeFee: '',
            oneTimeFeeCategory: '',
            hoursConfiguraitonAssistance: '',
            hoursEHSAdminTraining: '',
            hoursEndUserWebinars: '',
            hoursEndUserTraining: '',
            ischildElement: true,
            childElementTitle: 'Implementation Services',
            childElementSubTitle: 'Select Your Additional Implementation Services',
            childElementbutton: 'Add Services',
            childElements: [
                {
                    id: 1,
                    name: 'EHS Admin Training Via the Web',
                    isChecked: false,
                    description: 'Standard package includes configuration assistance via the web but no EHS Admin Training; add EHS Admin Web based Training to your standard package.',
                    longdescription: 'We provide X hours of IndustrySafe EHS Admin training  geared towards EHS Administrators.  We will review the configurations for all of your purchased modules and include exercises, instructions and case studies for the trainer. TRA’s training materials are all developed in-house by TRA staff who have in-depth experience in TRA’s software products, developing training materials, and conducting training sessions.',
                    perUserFees: 'No',
                    monthlyFee: '',
                    oneTimeFee: '',
                    hourlyFees: 125,
                    oneTimeFeeCategory: '',
                    hoursConfiguraitonAssistance: '',
                    hoursEHSAdminTraining: '',
                    hoursEndUserWebinars: '',
                    hoursEndUserTraining: ''
                }, {
                    id: 2,
                    name: 'End-User Webinars',
                    isChecked: false,
                    description: 'Standard package includes configuration assistance via the web but no End User Training; add End User Webinars to your standard package.',
                    longdescription: 'We provide X hours for end user webinars. We gear our webinars towards end users of the software and include 1 hour of end user webinar instruction with 1 hour of webinar preparation.  TRA will record all of the webinars, so that the webinars will be available for review by anyone from the Customer community (unable to attend the original webinar sessions).',
                    perUserFees: 'No',
                    monthlyFee: '',
                    oneTimeFee: '',
                    hourlyFees: 125,
                    oneTimeFeeCategory: '',
                    hoursConfiguraitonAssistance: '',
                    hoursEHSAdminTraining: '',
                    hoursEndUserWebinars: '',
                    hoursEndUserTraining: ''
                }, {
                    id: 3,
                    name: 'Configuration Assistance On-Site',
                    isChecked: false,
                    description: 'Standard package includes configuration assistance via the web replace web based assistance with on-site assistance.',
                    longdescription: 'Includes standard configuration assistance on-site at U.S. based Customer location with one of our skilled implementation managers (highly recommended for more effective configuration).   Customer is responsible for providing and setting up meetings and meeting facility.',
                    perUserFees: 'No',
                    monthlyFee: '',
                    oneTimeFee: 1500,
                    hourlyFees: '',
                    oneTimeFeeCategory: 'Travel',
                    hoursConfiguraitonAssistance: '',
                    hoursEHSAdminTraining: '',
                    hoursEndUserWebinars: '',
                    hoursEndUserTraining: '',
                    trainingOnSite: true
                }, {
                    id: 4,
                    name: 'EHS Admin Training On-Site',
                    isChecked: false,
                    description: 'Standard package includes configuration assistance via the web but no EHS Admin Training; add on-site EHS Admin Training to your standard package.',
                    longdescription: 'We provide X hours of IndustrySafe EHS Admin training  geared towards EHS Administrators on-site at your U.S. based customer location with one of our skilled implementation managers.  We will review the configurations for all of your purchased modules and include exercises, instructions and case studies for the trainer. TRA’s training materials are all developed in-house by TRA staff who have in-depth experience in TRA’s software products, developing training materials, and conducting training sessions. Customer is responsible for providing and setting up meetings and meeting facility.',
                    perUserFees: 'No',
                    monthlyFee: '',
                    oneTimeFee: 1500,
                    hourlyFees: '',
                    oneTimeFeeCategory: 'Travel',
                    hoursConfiguraitonAssistance: '',
                    hoursEHSAdminTraining: '',
                    hoursEndUserWebinars: '',
                    hoursEndUserTraining: '',
                    trainingOnSite: true
                }, {
                    id: 5,
                    name: 'End User Training On-Site',
                    isChecked: false,
                    description: 'Standard package includes configuration assistance via the web but no End User Training; add on-site End User Training to your standard package.',
                    longdescription: 'We provide X hours of IndustrySafe End User training  geared towards end users on-site at your U.S. based customer location with one of our skilled implementation managers for each module purchased.  Customer is responsible for providing and setting up meetings and meeting facility.',
                    perUserFees: 'No',
                    monthlyFee: '',
                    oneTimeFee: 1500,
                    hourlyFees: '',
                    oneTimeFeeCategory: 'Travel',
                    hoursConfiguraitonAssistance: '',
                    hoursEHSAdminTraining: '',
                    hoursEndUserWebinars: '',
                    hoursEndUserTraining: '',
                    trainingOnSite: true
                }]
        },
{
    id: 5,
    name: 'Mobile App- $24 a month not including fees payable to Canvas',
    isChecked: false,
    description: 'Mobile App for Inspections in partnership with Canvas',
    longdescription: ' IndustrySafe’s Mobile app allows users to conduct inspections in the field. Designed specifically for smart phones and tablet devices, the mobile app is easy to use and can be used with or without web access. Inspection data is synched with the IndustrySafe database for real time reporting and analytics.',
    perUserFees: 'Yes',
    monthlyFee: 24,
    oneTimeFee: '',
    oneTimeFeeCategory: '',
    hoursConfiguraitonAssistance: 8,
    hoursEHSAdminTraining: 2,
    hoursEndUserWebinars: 2,
    hoursEndUserTraining: 2,
    ischildElement: false,
    childElementTitle: '',
    childElementSubTitle: '',
    childElementbutton: '',
    childElements: []
}];